# Generated by Django 4.0.5 on 2022-07-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_profile_last_emotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='cloudinary_storage.storage.MediaCloudinaryStorage/images/default_image_qvmqoi.png', upload_to='images'),
        ),
    ]
