# Generated by Django 4.0.5 on 2022-06-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording', models.FileField(upload_to='EmotionTalk/AI_emotion_recognizer/recordings/')),
                ('owner_id', models.IntegerField()),
            ],
        ),
    ]
