# Generated by Django 4.0.5 on 2022-06-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_talk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='recording',
            field=models.FileField(upload_to='EmotionTalk/EmotionTalk/AI_emotion_recognizer/recordings'),
        ),
    ]
